# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

# stages:
# - stage: Test
#   displayName: Run Tests
#   jobs:
#     - job:
# steps: 
# - task: CmdLine@2
#   inputs:
#     script: 'echo your tests are passed'
# stages:
  # - stage:
steps:
  - task: CmdLine@2
    inputs:
      script: 'echo test ran'

# - stage: Build
#   displayName: Build image
#   jobs:
#   - job: Build
#     displayName: Build
#     pool:
#       vmImage: ubuntu-latest
#     steps:
#     - task: Docker@2
#       displayName: Build an image
#       inputs:
#         command: build
#         dockerfile: '$(Build.SourcesDirectory)/dockerfile'
#         tags: |
#           $(tag)
