name: Run npm tests

on:
  push:
    branches:
      - main
    paths-ignore:
    - '.github/workflows/**'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (with version 16 in this case)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # # Step 4: Run tests
      # - name: Run tests
      #   run: npm test
